### PR TITLE
feat(share-video) update share video tests to include generic video s…

### PR DESCRIPTION
**Pull request by quitrk**
…haring

### CODE REVIEW

**Comment by damencho** [comment]
Is youtube sharing still supported?

**Comment by damencho** [comment]
If so, let's keep both tests then.

**Comment by quitrk** [comment]
> If so, let's keep both tests then.

they're both tested...first link is still a youtube link

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Yep ... I missewd that, mind that this needs to be merged at the same time as the jitsi-meet change. 

Why did you drop the `volumeTest `?

**Comment by quitrk** [comment]
> Yep ... I missewd that, mind that this needs to be merged at the same time as the jitsi-meet change.
> 
> Why did you drop the `volumeTest `?

we're not syncing the video volume anymore

**Pull request merged**
