### PR TITLE
fix(avatar) Fix tests

### PR DESCRIPTION
**Pull request by robertpin**
The new default avatar is an icon, not an image of an icon

### CODE REVIEW

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by robertpin** [comment]
Jenkins test this please

**Comment by robertpin** [comment]
Jenkins test this please

**Review by dudumanbogdan — APPROVED** [review]
lgtm👍

**Pull request merged**
