### PR TITLE
Fix tests for new DisplayNameBadge

### PR DESCRIPTION
**Pull request by muscat1**
https://github.com/jitsi/jitsi-meet/pull/9416

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins add to whitelist.

**Comment by muscat1** [comment]
Jenkins please test this please.

**Comment by muscat1** [comment]
Jenkins please test this please.

**Comment by muscat1** [comment]
Jenkins please test this please.

**Comment by muscat1** [comment]
Jenkins please test this please.

**Comment by muscat1** [comment]
Jenkins please test this please.

**Pull request closed without merging**
