### PR TITLE
feat: update to test components with improved accessibility

### PR DESCRIPTION
**Pull request by emrahcom**
This PR updates breakout-room and av-moderation scripts to test buttons and context menu with improved accessibility after https://github.com/jitsi/jitsi-meet/pull/13669.

These tests also work with the current master branch.

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins test this please.

**Comment by emrahcom** [comment]
@damencho, Jenkins test looks failed. Is it related with this PR or something else..?

I tested updated test scripts against `stable-8960` (_my local Jitsi setup_) and `alpha.jitsi.net` and they all passed.

```bash
mvn test -DallowInsecureCerts=true \
  -Djitsi-meet.tests.toRun="BreakoutRoomsTest,AudioVideoModerationTest" \
  -Djitsi-meet.instance.url="https://alpha.jitsi.net"
```

**Comment by damencho** [comment]
O you know, there was a broken node in our grid. I will re-run it.

**Comment by damencho** [comment]
Now it looks better. Not that I see what is the problem:
```
element click intercepted: Element <button aria-label="More moderation options" class="iconButton css-15qz9wz-button-secondary-iconButton-medium" id="participants-pane-context-menu" title="More moderation options" type="button" data-focus-on-hidden="true" aria-hidden="true">...</button> is not clickable at point (1356, 556). Other element would receive the click: <div class="css-197os2p-footerMoreContainer">...</div>
```

org jitsi meet test AudioVideoModerationTest-web participant1

Not sure what is that footerMoreContainer ...

**Comment by emrahcom** [comment]
Is this the result against [this PR](https://github.com/jitsi/jitsi-meet/pull/13669)?
If so that means I'm missing something

**Comment by damencho** [comment]
I think so.

You can can see in https://pr-reports.jitsi.org/jitsi-meet-torture-PR-test/1094/log.txt
```
+ git pull https://github.com/nordeck/jitsi-meet-torture-2.git nic/feat/accessibility/brekout
+ git pull https://github.com/nordeck/jitsi-meet.git nic/feat/accessibility/brekout
From https://github.com/nordeck/jitsi-meet
```

**Comment by emrahcom** [comment]
Finally I can reproduce the same issue on my local after switching `Chrome 117`

**Comment by emrahcom** [comment]
@damencho, could you test it again please.

I updated `unfocus` method while closing the context menu.

**Comment by damencho** [comment]
Jenkins, test this please.

**Review by Calinteodor — APPROVED** [review]

**Pull request merged**
