### PR TITLE
fix(preJoin): Configuration parameters for preJoin scenarios

### PR DESCRIPTION
**Pull request by rjhernandez**
# FIX: PreJoin Tests
Updated the `preJoin` tests to match the latest `config.js` changes in `jitsi-meet` version `6726`.

### CODE REVIEW

**Comment by damencho** [comment]
Seems it breaks preJoin test

**Comment by rjhernandez** [comment]
> Seems it breaks preJoin test

Will verify and close the PR if needed, I was certain that the tests were breaking before and now were passing on my instance.  

Thanks your time @damencho!

**Comment by rjhernandez** [comment]
If possible, can we run another build on this changes.
I made a silly mistake on the original commit. 🤷 

*Case issue:
`"preJoinConfig != prejoinConfig"`

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by rjhernandez** [comment]
Any chance we could get an approval?
@damencho

**Review by damencho — APPROVED** [review]

**Pull request merged**
