### PR TITLE
fix(av-moderation) Fix advanced moderation tests

### PR DESCRIPTION
**Pull request by robertpin**

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins add to whitelist.

**Comment by damencho** [comment]
Some code styles need fixing.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Comment by robertpin** [comment]
Jenkins, test this please.

**Review by horymury — APPROVED** [review]

**Pull request merged**
