### PR TITLE
fix(MobileParticipant): fix permissions on the welcome page

### PR DESCRIPTION
**Pull request by saghul**
No permissions are requested any longer. Camera and mic permissions are
now requeted when joining.

### CODE REVIEW

**Comment by paweldomas** [comment]
The tests have failed because the iOS build got stuck. Not sure why. I'm giving it another try:
https://travis-ci.org/jitsi/jitsi-meet/builds

**Comment by paweldomas** [comment]
Download and extract the tests-report.zip from here: http://ci.jitsi.org/view/pr-testing/job/jitsi-meet-torture-PR-test/219/
I'll write a manual on how to run mobile tests locally today

**Comment by paweldomas** [comment]
It looks like it didn't accept the camera permissions for some reason. Lets see what happens after one more try.

**Comment by saghul** [comment]
> I'll write a manual on how to run mobile tests locally today

Thank you!



> It looks like it didn't accept the camera permissions for some reason. Lets see what happens after one more try.

Hum, the whole point of this PR is that no camera permissions are requested :-) I guess it will run with the jitsi-meet build with the same branch name, right?

**Comment by paweldomas** [comment]
Yes, it's supposed to run with the same branch name. After restart it failed with the 64 error code, but now Boris dismissed the dialog and I'm giving it another try.

**Comment by saghul** [comment]
> On the screenshot it looks like it asks for camera permissions. So you're saying that it shouldn't ask ?

Correct. Which is what I observe when I test manually.

> I wonder if something's broken with branching and maybe the PR is not taking the jitsi-meet branch correctly or something.

This is my suspicion. Somehow Android works though.

**Comment by saghul** [comment]
No problem @paweldomas! Thanks a lot for fixing that! ❤️

**Pull request merged**
