### PR TITLE
fix(sharedvideotest) added id for click event

### PR DESCRIPTION
**Pull request by Calinteodor**

### CODE REVIEW

**Review by saghul — DISMISSED** [review]

**Comment by saghul** [comment]
Jenkins add to whitelist.

**Comment by saghul** [comment]
Jenkins please test this please.

**Review by saghul — APPROVED** [review]

**Comment by damencho** [comment]
Hey we should not have merged this before passing, and we needed to merge it at the same time as the jitsi-meet PR

**Comment by saghul** [comment]
http://pr-reports.jitsi.org/jitsi-meet-PR-test/8771 they did pass.

**Comment by damencho** [comment]
But the test was not correct, was not checking anything ... anyway

**Comment by saghul** [comment]
I'll admit I haven't checked every line, but it didn't pass before and it does now after the change in the language file.
 Happy to discuss how to improve the test!

**Pull request merged**
