### PR TITLE
feat: Add grant moderator test

### PR DESCRIPTION
**Pull request by gimre**

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins add to whitelist.

**Comment by damencho** [comment]
Jenkins add to whitelist.

**Comment by damencho** [comment]
Jenkins test this please.

**Comment by damencho** [comment]
@gimre Is this supposed to be tested with https://github.com/jitsi/jitsi-meet/pull/7248?
If so, both PRs should have the same branch name.

**Comment by gimre** [comment]
oh, gotcha, thanks!

**Pull request closed without merging**
